In [1]:
import tensorflow as tf
tf.__version__

'2.10.0'

In [3]:
mnist = tf.keras.datasets.mnist

In [4]:
(x_train, y_train) , (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 1s 0us/step


#### Building a Model

In [5]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [6]:
predtictions = model(x_train[:1]).numpy()
predtictions

array([[-0.17034343,  1.0627759 ,  0.137091  ,  1.1161599 ,  0.22543328,
        -0.77398753,  0.10187933, -0.92389655,  0.33811033, -0.504731  ]],
      dtype=float32)

In [7]:
tf.nn.softmax(predtictions).numpy()

array([[0.06407638, 0.21990487, 0.08713949, 0.23196329, 0.09518787,
        0.03503794, 0.08412457, 0.03016019, 0.10654097, 0.04586435]],
      dtype=float32)

In [8]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [9]:
loss_fn(y_train[:1], predtictions).numpy()

3.3513236

In [10]:
model.compile(optimizer='adam',
              loss = loss_fn,
              metrics = ['accuracy'])

In [12]:
!pip install ipython-autotime

In [13]:
%load_ext autotime

time: 0 ns (started: 2022-11-06 15:37:32 +00:00)


In [15]:

model.fit(x_train,y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0304 - accuracy: 0.9894
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0311 - accuracy: 0.9893
Epoch 3/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0292 - accuracy: 0.9901
Epoch 4/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0290 - accuracy: 0.9902
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0262 - accuracy: 0.9908


time: 33.7 s (started: 2022-11-06 15:38:38 +00:00)


In [16]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0779 - accuracy: 0.9806 - 995ms/epoch - 3ms/step


[0.07787316292524338, 0.9805999994277954]

time: 1.08 s (started: 2022-11-06 15:39:51 +00:00)


In [17]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.7588060e-13, 5.0831615e-17, 1.7298911e-13, 7.1815371e-08,
        8.1499740e-15, 2.0885654e-10, 4.5164827e-20, 9.9999988e-01,
        1.4261092e-11, 5.3684506e-09],
       [6.6468163e-12, 4.1322397e-11, 1.0000000e+00, 2.0335524e-10,
        1.6052798e-28, 1.1954692e-16, 1.8739490e-15, 1.3013802e-27,
        6.4064823e-13, 1.6899285e-20],
       [1.9624656e-10, 9.9998951e-01, 3.7618986e-07, 2.0905815e-09,
        1.0266760e-07, 8.7011204e-10, 7.1052042e-08, 8.3108516e-06,
        1.7262570e-06, 1.0495144e-11],
       [9.9998653e-01, 4.1129038e-11, 1.4212074e-08, 1.9603040e-11,
        1.4179546e-13, 1.7773617e-08, 1.3413435e-05, 5.5314642e-12,
        1.1886936e-12, 1.4086736e-09],
       [1.8695033e-12, 1.6672123e-21, 9.9354647e-10, 4.7908234e-14,
        9.9996746e-01, 2.0171602e-11, 2.2001248e-13, 7.2914304e-08,
        2.1145494e-12, 3.2391697e-05]], dtype=float32)>

time: 31 ms (started: 2022-11-06 15:40:25 +00:00)
